name: Release

run-name: Release

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    release:
        runs-on: windows-latest
        permissions:
          contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8.10'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Build
              run: |
                pyinstaller.exe -F main.py --clean --distpath=. -n "${{github.event.repository.name}}.${{github.ref_name}}"
      
            - name: Zip
              run: |
                git archive --format=zip --output=${{github.event.repository.name}}.${{github.ref_name}}.zip HEAD bin 使用说明.txt --add-file ${{github.event.repository.name}}.${{github.ref_name}}.exe -v

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{github.event.repository.name}}.${{github.ref_name}}
                path: ${{github.event.repository.name}}.${{github.ref_name}}.zip

            - name: Create Release
              uses: softprops/action-gh-release@v2.3.2
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              with:
                fail_on_unmatched_files: true
                files: "${{github.event.repository.name}}.${{github.ref_name}}.zip"